# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '3-Days' do
  
  use_frameworks!

  # Pods for 3-Days
  pod 'Alamofire', '~> 5.8'
  pod 'SCLAlertView', '~> 0.8'
  pod 'SDWebImage', '~> 5.0'
  pod 'ImageSlideshow', '~> 1.9'
  pod "ImageSlideshow/SDWebImage", '~> 1.9'
  pod 'SQLite.swift', '~> 0.14'

end
